parameters:
#    sophi_user.example.class: Sophi\UserBundle\Example

services:
#    sophi_user.example:
#        class: %sophi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sophi_user.registration.form.type:
        class:     Sophi\UserBundle\Form\Type\RegistrationFormType
        arguments:     [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sophi_user_registration }